env:
  global:
    - BUILD_CONFIG=Debug
    - RUN_CONFIG=Release
matrix:
  include:
    - name: "Windows - c"
      os: windows
      language: c
      env: 
        - VS15=true
        - NMAKE_PATH="/c/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/amd64_x86/"
      script:
        - dir /c/Program Files (x86)/
        - cl -EHsc main.c
        - cmake --build . --config $BUILD_CONFIG -- -m
        - ls $BUILD_CONFIG
       
install:
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then
      choco install -y python3 --version 3.8.1;
      if [[ "$VS15" == "true" ]]; then
        choco install -y vcbuildtools --version 2015.4 --force;
      fi;
    fi
