# Windows (https://github.com/travis-ci-tester/toolchain-table)

environment:
  matrix:
    ###
    - TOOLCHAIN: "vs-14-2015"
      CONFIG: Release

    - TOOLCHAIN: "vs-14-2015"
      CONFIG: Debug

install:

  # Check versions of tools
  - cmd: where cmake
  - cmd: cmake --version

build_script:
  - cmd: cl -EHsc main.c --toolchain "%TOOLCHAIN%" --config "%CONFIG%" --verbose --test
